### ISSUE TITLE
Fail to decompress with 7z file containing *.exe file

### ISSUE THREAD

**Issue by PoyExe** [bodgit/sevenzip#13] opened 2022-02-20 14:07 UTC
![16451838696520](https://user-images.githubusercontent.com/67918217/154846617-bb5fb135-8bac-447a-b874-c94e841d07e2.png)

**Comment by bodgit** [comment] 2022-02-28 09:16
Probably a duplicate of #6 (missing BCJ2 support)

**Comment by bodgit** [comment] 2022-04-29 17:14
If #15 doesn't fix this, can you provide one of the following, in descending order of preference:

* A small example .7z file that demonstrates the issue
* A URL link to a file I can download myself
* The output from `7z l -slt file.7z` so it shows the compression methods used in the file

**Closed** 2022-04-29 17:15 UTC
